name: Sync GitHub to GitLab

on:
  push:
    branches:
      - "**" # Trigger für alle Branches

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Holt alle Branches

      - name: Push all branches to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/develop.faist/jmix.git
          git push --mirror --prune gitlab