name: Sync GitHub to GitLab

on:
  push:
    branches:
      - "**" # Trigger für alle Branches

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Holt alle Commits & Historie

      - name: Fetch all branches from GitHub
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch --prune  # Holt ALLE Branches & entfernt alte
          git branch -r  # Debug: Zeigt alle Remote-Branches an

      - name: Push all branches to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/develop.faist/jmix.git
          
          # Hole alle Branches aus GitHub
          for branch in $(git branch -r | grep -v 'HEAD' | sed 's/origin\///'); do
            echo "Processing branch: $branch"

            # Prüfe, ob der Branch bereits in GitLab existiert
            if git ls-remote --exit-code --heads gitlab $branch; then
              echo "Branch $branch exists in GitLab. Pushing updates..."
            else
              echo "Branch $branch does NOT exist in GitLab. Creating it..."
              git push gitlab origin/$branch:refs/heads/$branch
            fi

            # Pushen der Änderungen
            git push --prune gitlab origin/$branch:refs/heads/$branch
          done

          # Pusht alle Tags
          git push --prune gitlab --tags
