name: Sync GitHub to GitLab

on:
  push:
    branches:
      - "**" # Trigger für alle Branches

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Holt alle Commits & Historie

      - name: Fetch all branches
        run: |
          git fetch --prune --unshallow
          git fetch origin "+refs/heads/*:refs/remotes/origin/*" # Holt ALLE Branches
          git branch -r  # Debug: Zeigt alle Remote-Branches an

      - name: Push all branches and tags to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/develop.faist/jmix.git
          git push --prune gitlab "refs/remotes/origin/*:refs/heads/*"  # Push alle Branches
          git push --prune gitlab --tags  # Push alle Tags
